
export const EVENTS = {
    SEND_MESSAGE: "SEND_MESSAGE",
    RECEIVE_NOTIFICATION: "RECEIVE_NOTIFICATION",
    REGISTER_USER: "REGISTER_USER",
    RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
    JOIN_CHAT: "JOIN_CHAT"
}